   Compiling c2rust_out v0.0.0 (/home/c00834010/dev/crusts-benchmarks/2023-06-27/continued_fraction)
error: unsafe block missing a safety comment
  --> src/main.rs:23:5
   |
23 |     unsafe {
   |     ^^^^^^^^
   |
   = help: consider adding a safety comment on the preceding line
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#undocumented_unsafe_blocks
   = note: requested on the command line with `-D clippy::undocumented-unsafe-blocks`

error: used `expect()` on an `Option` value
  --> src/main.rs:25:17
   |
25 |             a = f_a.expect("non-null function pointer")(i);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: if this value is `None`, it will panic
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_used
   = note: requested on the command line with `-D clippy::expect-used`

error: used `expect()` on an `Option` value
  --> src/main.rs:26:17
   |
26 |             b = f_b.expect("non-null function pointer")(i);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: if this value is `None`, it will panic
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_used

error: used `expect()` on an `Option` value
  --> src/main.rs:31:13
   |
31 |         a = f_a.expect("non-null function pointer")(0);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: if this value is `None`, it will panic
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_used

error: default numeric fallback might occur
  --> src/main.rs:91:12
   |
91 |     return 0;
   |            ^ help: consider adding suffix: `0_i32`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_numeric_fallback
   = note: requested on the command line with `-D clippy::default-numeric-fallback`

error: could not compile `c2rust_out` (bin "main") due to 5 previous errors
